package com.spring.movie.domain;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pelicula generated by hbm2java
 */
public class Pelicula implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1677776615976816538L;
	private Integer idPelicula;
	private Actor productor;
	private Actor director;
	private Pais pais;
	private Genero genero;
	private String titulo;
	private Integer tiempoMinutos;
	private Date fechaLanzamiento;
	private String comentarios;
	
	private Set<Actor> actoresDeReparto = new HashSet<Actor>();

	public Pelicula() {
	}

	public Pelicula(Actor productor, Actor director, Pais pais, 
			Genero genero, String titulo, Integer tiempoMinutos,
			Date fechaLanzamiento) {
		this.productor = productor;
		this.director = director;
		this.pais = pais;
		this.genero = genero;
		this.titulo = titulo;
		this.tiempoMinutos = tiempoMinutos;
		this.fechaLanzamiento = fechaLanzamiento;
	}

	public Pelicula(Actor productor, Actor director, Pais pais, 
			Genero genero, String titulo, int tiempoMinutos,
			Date fechaLanzamiento, String comentarios) {
		this.productor = productor;
		this.director = director;
		this.pais = pais;
		this.genero = genero;
		this.titulo = titulo;
		this.tiempoMinutos = tiempoMinutos;
		this.fechaLanzamiento = fechaLanzamiento;
		this.comentarios = comentarios;
	}

	public Integer getIdPelicula() {
		return this.idPelicula;
	}

	public void setIdPelicula(Integer idPelicula) {
		this.idPelicula = idPelicula;
	}

	public Actor getProductor() {
		return productor;
	}

	public void setProductor(Actor productor) {
		this.productor = productor;
	}

	public Actor getDirector() {
		return director;
	}

	public void setDirector(Actor director) {
		this.director = director;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public Genero getGenero() {
		return this.genero;
	}

	public void setGenero(Genero genero) {
		this.genero = genero;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public int getTiempoMinutos() {
		return this.tiempoMinutos;
	}

	public void setTiempoMinutos(int tiempoMinutos) {
		this.tiempoMinutos = tiempoMinutos;
	}

	public Date getFechaLanzamiento() {
		return this.fechaLanzamiento;
	}

	public void setFechaLanzamiento(Date fechaLanzamiento) {
		this.fechaLanzamiento = fechaLanzamiento;
	}

	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	private String nombreProductor;	
	private String nombreDirector;	
	private String nombrePais;	
	private String nombreGenero;
	
	public String getNombreProductor() {
		return nombreProductor;
	}

	public void setNombreProductor(String nombreProductor) {
		this.nombreProductor = nombreProductor;
	}

	public String getNombreDirector() {
		return nombreDirector;
	}

	public void setNombreDirector(String nombreDirector) {
		this.nombreDirector = nombreDirector;
	}

	public String getNombrePais() {
		return nombrePais;
	}

	public void setNombrePais(String nombrePais) {
		this.nombrePais = nombrePais;
	}

	public String getNombreGenero() {
		return nombreGenero;
	}

	public void setNombreGenero(String nombreGenero) {
		this.nombreGenero = nombreGenero;
	}

	public void setTiempoMinutos(Integer tiempoMinutos) {
		this.tiempoMinutos = tiempoMinutos;
	}

	public Set<Actor> getActoresDeReparto() {
		return actoresDeReparto;
	}

	public void setActoresDeReparto(Set<Actor> actoresDeReparto) {
		this.actoresDeReparto = actoresDeReparto;
	}



	@Override
	public String toString() {
		return "Pelicula [idPelicula=" + idPelicula + ", productor="
				+ productor + ", director=" + director + ", pais=" + pais
				+ ", genero=" + genero + ", titulo=" + titulo
				+ ", tiempoMinutos=" + tiempoMinutos + ", fechaLanzamiento="
				+ fechaLanzamiento + ", comentarios=" + comentarios
				+ ", actoresDeReparto=" + actoresDeReparto + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((comentarios == null) ? 0 : comentarios.hashCode());
		result = prime * result
				+ ((director == null) ? 0 : director.hashCode());
		result = prime
				* result
				+ ((fechaLanzamiento == null) ? 0 : fechaLanzamiento.hashCode());
		result = prime * result + ((genero == null) ? 0 : genero.hashCode());
		result = prime * result
				+ ((idPelicula == null) ? 0 : idPelicula.hashCode());
		result = prime * result + ((pais == null) ? 0 : pais.hashCode());
		result = prime * result
				+ ((productor == null) ? 0 : productor.hashCode());
		result = prime * result
				+ ((tiempoMinutos == null) ? 0 : tiempoMinutos.hashCode());
		result = prime * result + ((titulo == null) ? 0 : titulo.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pelicula other = (Pelicula) obj;
		if (comentarios == null) {
			if (other.comentarios != null)
				return false;
		} else if (!comentarios.equals(other.comentarios))
			return false;
		if (director == null) {
			if (other.director != null)
				return false;
		} else if (!director.equals(other.director))
			return false;
		if (fechaLanzamiento == null) {
			if (other.fechaLanzamiento != null)
				return false;
		} else if (!fechaLanzamiento.equals(other.fechaLanzamiento))
			return false;
		if (genero == null) {
			if (other.genero != null)
				return false;
		} else if (!genero.equals(other.genero))
			return false;
		if (idPelicula == null) {
			if (other.idPelicula != null)
				return false;
		} else if (!idPelicula.equals(other.idPelicula))
			return false;
		if (pais == null) {
			if (other.pais != null)
				return false;
		} else if (!pais.equals(other.pais))
			return false;
		if (productor == null) {
			if (other.productor != null)
				return false;
		} else if (!productor.equals(other.productor))
			return false;
		if (tiempoMinutos == null) {
			if (other.tiempoMinutos != null)
				return false;
		} else if (!tiempoMinutos.equals(other.tiempoMinutos))
			return false;
		if (titulo == null) {
			if (other.titulo != null)
				return false;
		} else if (!titulo.equals(other.titulo))
			return false;
		return true;
	}
	
	
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pelicula")
//	public Set<ActorPelicula> getActorPeliculas() {
//		return this.actorPeliculas;
//	}
//
//	public void setActorPeliculas(Set<ActorPelicula> actorPeliculas) {
//		this.actorPeliculas = actorPeliculas;
//	}
	
	

}
